<?php
/**
 * RoleEnumTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ensi\AdminAuthClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ensi Admin Auth
 *
 * Авторизация системных пользователей
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mail@greensight.ru
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ensi\AdminAuthClient;

use PHPUnit\Framework\TestCase;

/**
 * RoleEnumTest Class Doc Comment
 *
 * @category    Class
 * @description Роли. Расшифровка значений:   * &#x60;101&#x60; - Администратор   * &#x60;102&#x60; - Супер-администратор   * &#x60;106&#x60; - Продукт менеджер   * &#x60;103&#x60; - Менеджер продавцов   * &#x60;104&#x60; - Менеджер клиентов   * &#x60;115&#x60; - Администратор магазина   * &#x60;116&#x60; - SEO менеджер   * &#x60;120&#x60; - OMS. Администратор смены   * &#x60;119&#x60; - OMS. Сборщик   * &#x60;111&#x60; - OMS. Комплектовщик   * &#x60;113&#x60; - OMS. Оператор call-центра   * &#x60;114&#x60; - OMS. Сотрудник магазина   * &#x60;112&#x60; - OMS. Логист   * &#x60;201&#x60; - Оператор продавца   * &#x60;202&#x60; - Администратор продавца
 * @package     Ensi\AdminAuthClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RoleEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RoleEnum"
     */
    public function testRoleEnum()
    {
    }
}
